=== TaciturnCoder/Consortium/docs/schema/0.0.4.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "definitions": {
        "version": {
            "type": "object",
            "properties": {
                "revision": {
                    "type": "integer"
                },
                "patch": {
                    "type": "integer"
                },
                "draft": {
                    "type": "integer"
                },
                "release": {
                    "type": "string"
                },
                "build": {
                    "type": "string"
                }
            },
            "required": [
                "revision",
                "patch",
                "draft"
            ]
        },
        "runner": {
            "type": "object",
            "properties": {
                "scripts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "parameters": {
                    "type": "string"
                }
            },
            "required": [
                "scripts"
            ]
        }
    },
    "properties": {
        "$schema": {
            "type": "string"
        },
        "version": {
            "$ref": "#/definitions/version"
        },
        "editor": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "vscode"
                ]
            },
            "additionalItems": false
        },
        "license": {
            "type": "object",
            "properties": {
                "year": {
                    "type": "string",
                    "pattern": "^\\d{4}(-\\d{2}\\d{2}?)?$"
                },
                "licensor": {
                    "type": "object",
                    "properties": {
                        "author": {
                            "type": "string"
                        },
                        "mail": {
                            "type": "string"
                        },
                        "web": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "author",
                        "mail"
                    ]
                }
            },
            "required": [
                "year",
                "licensor"
            ]
        },
        "runners": {
            "type": "object",
            "patternProperties": {
                "^[A-Za-z0-9_]+$": {
                    "$ref": "#/definitions/runner"
                }
            }
        }
    },
    "required": [
        "version",
        "license"
    ],
    "additionalProperties": false
}

=== TaciturnCoder/Consortium/.consortium.json
{
    "$schema": "src/schema/schema.json",
    "version": {
        "revision": 0,
        "patch": 0,
        "draft": 4
    },
    "editor": [
        "vscode"
    ],
    "license": {
        "year": "2022",
        "licensor": {
            "author": "Dwij Bavisi",
            "mail": "dwijbavisi@gmail.com"
        }
    },
    "runners": {
        "init": {
            "scripts": [
                "src/git/setup.sh",
                "src/editor/setup.sh"
            ]
        },
        "setup": {
            "scripts": [
                "src/editor/setup.sh"
            ]
        },
        "build-schema": {
            "scripts": [
                "build/schema.sh",
                "build/clean.sh"
            ]
        }
    }
}
